Repository rust-bitcoin/rust-bitcoincore-rpc, pull requests merged in 2020-05, with the labels that each got.

#104 Add missing "orphan" variant for GetTransactionResultDetailCategory
  json/src/lib.rs
Labels: bug, enhancement

#105 Update logging handling
  client/src/client.rs
Labels: enhancement

#109 Fix some fields in the GetPeerInfoResult struct
  client/src/client.rs
  json/src/lib.rs
Labels: bug
